before:
  hooks:
    - go mod tidy
checksum:
  disable: true 
snapshot:
  name_template: "SNAPSHOT-{{.ShortCommit}}"
builds:
  - id: default
    goos:
      - darwin
    goarch:
      - amd64
    ldflags: "-X github.com/progrium/macschema/cmd.Version={{.Version}}"
    hooks:
      post: './tools/gonutil {{.Version}}'
archives:
- id: default
  builds:
  - default
  name_template: '{{ .ProjectName }}_{{ .Version }}'
  format: zip
  files:
  - none*
signs:
  - id: notarize
    signature: "${artifact}.zip"
    cmd: gon
    args: ["./dist/gon_notarize.json"]
    artifacts: all
release:
  github:
    owner: progrium
    name: macschema
  ids:
    - default
  draft: true
